export const BASE_URL = 'https://www.wanandroid.com'

/*公众号作者列表*/
export const GROUP_AUTHOR_LIST = `${BASE_URL}/wxarticle/chapters/json`
/*推荐文章列表*/
export const ARTICLE_RECOMMEND_LIST = `${BASE_URL}/article/list/`
/*广场文章列表*/
export const ARTICLE_SQUARE_LIST = `${BASE_URL}/user_article/list/`
/*问答列表*/
export const QA_LIST = `${BASE_URL}/wenda/list/`
/*首页banner*/
export const BANNER = `${BASE_URL}/banner/json/`
/**
 * 获取我的积分列表
 */
export const COIN_LIST = `${BASE_URL}/lg/coin/list/`
/**
 * 获取积分排行榜
 */
export const COIN_RANK = `${BASE_URL}/coin/rank/`
/**
 * 获取收藏列表
 */
export const COLLECTION_LIST = `${BASE_URL}/lg/collect/list/`
/**
 * 收藏站内文章
 */
export const COLLECTION_ARTICLE = `${BASE_URL}/lg/collect/`
/**
 * 取消收藏
 */
export const UN_COLLECTION = `${BASE_URL}/lg/uncollect_originId/`
/**
 * 根据作者id获取文章/获取作者文章
 */
export const ARTICLE_FOR_AUTHOR = `${BASE_URL}/wxarticle/list/`
/**
 * 获取项目列表
 */
export const PROJECT_LIST = `${BASE_URL}/project/list/`
/**
 * 获取‘最新项目’列表
 */
export const NEW_PROJECT_LIST = `${BASE_URL}/article/listproject/`
/**
 *  获取项目分类
 */
export const PROJECT_CLASSIFY = `${BASE_URL}/project/tree/json`
/**
 *  登录
 */
export const LOGIN = `${BASE_URL}/user/login`
/**
 *  获取用户信息
 */
export const USER_INFO = `${BASE_URL}/user/lg/userinfo/json`
/**
 *  工具列表
 */
export const TOOL_LIST = `${BASE_URL}/tools/list/json`
