export default class AuthorModel {
    name: string = ''
    id: number = -1
    articleList: string[] =[]
    author: string = ''
    children: string[] =[]
    courseId: number = -1
    cover: string = ''
    desc: string = ''
    lisense: string = ''
    lisenseLink: string = ''
    order: number = -1
    parentChapterId: number = -1
    type: number = -1
    userControlSetTop: boolean = false
    visible: number = -1
}