
export default class Constants {
  static readonly HOME_TITLE = '首页';
  static readonly MINE_TITLE = '我的';
  static readonly SERIES_TITLE = '体系';
  static readonly PROJECT_TITLE = '项目';
  static readonly OFFICIALACOUNT_TITLE = '公众号';
  static readonly HOME_TAB_INDEX = 0;
  static readonly PROJECT_TAB_INDEX = 1;
  static readonly OFFICIALACOUNT_TAB_INDEX = 3;
  static readonly SERIES_TAB_INDEX = 2;
  static readonly MINE_TAB_INDEX = 4;
  static readonly RECOMMENDED_TITLE = '推荐';
  static readonly SQUARE_TITLE = '广场';
  static readonly ANSWER_TITLE = '问答';
  static readonly FULL_PARENT = '100%';
  static readonly TAB_WIDTH = '100%';

  static readonly REFRESH_ICON_WIDTH = 40;
  static readonly REFRESH_ICON_HEIGHT = 40;
  static readonly BANNER_HEIGHT = '27%';
  static readonly BANNER_BORDER_RADIUS = 12;

}



